import pandas as pd

translation_dict = {
      'Data - Gestion Pladifes': 'Data - Pladifes - Gestion Pladifes',
      'Data - Densités sectorielles': '_Terminé - Data - Pladifes - Densités sectorielles',
      'Congés': 'ILB - Congés & Arrêts (hors jours fériés)',
      'Labs - Communication Labs': 'Labs - Communication Int/Ext',
      'Data - CGEE': 'Data - Pladifes - COGEM', 
      'Data - Bottom-up': 'Data - Pladifes - Bottom-up',
      'Data - Challenge Data - Beta Testing': 'Data - Labs - Challenge Data - Beta Testing',
      'Labs - Prospection': 'Labs - Prospection',
      'Data - Recrutement': 'Labs - Recrutement',
      'tâche interne - Atelier': "Labs - Préparation présentation d'équipe",
      'tâche interne - Evenement': "Labs - Préparation événement",
      "Labs - Réunion d'équipe": 'Labs - Réunions internes',
      'Labs - Participation événement': 'Labs - Participation événement',
      'Labs - Préparation événement': 'Labs - Préparation événement',
      "Tâche interne récurrente - Présentation d'équipe": "Labs - Préparation présentation d'équipe",
      'Data - Réplication WBS': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'Labs - RH & suivi collaborateur': 'Labs - RH & suivi collaborateur',
      'Data - Formation': 'Labs - Formation',
      'Kanban - Stratégie': 'Kanban - Stratégie',
      'Labs - Congés': 'ILB - Congés & Arrêts (hors jours fériés)',
      'ESG - CAA Alignement Agri': '_Terminé - ESG - CAA - Alignement Agri - AVENANT 0',
      'Labs - Newsletter ESG Lab': 'Labs - Newsletter ESG',
      'Labs - Recrutement': 'Labs - Recrutement',
      'Tâche interne récurrente - Réunions internes': 'Labs - Réunions internes',
      'ESG - CAA Alignement Automoteur Agricole': 'ESG - CAA - Alignement & Empreinte carbone - AVENANT 3', 
      'Tâche interne récurrente - Outils mixtes (ressources web, sites, référencement des ressources, medium, PowerBI, CV, photos…)': 'Labs - Tâches interne (autres)', ##? séparer entre les champs
      'tâche interne - Photos': 'Labs - Photo',
      'Labs - Formation': 'Labs - Formation',
      'ESG - CAA Alignement Immo': '_Terminé - ESG - CAA - Alignement Immo - AVENANT 0',
      'Tâche interne récurrente - News et newsletters': 'Labs - Newsletter ESG', 
      'Data - BNPP PF Data Next': '_Terminé - Data - BNPP PF - Data Next - AVENANT 0',
      'Data - Yap': '_Terminé - Data - Yap - Credit scoring - AVENANT 0',
      'Kanban - Standardisation des prez': 'Kanban - _Terminé - Standardisation des prez', 
      'Data - Kearney CFA': '_Terminé - Data - Kearney - CFA - AVENANT 0',
      'Kanban - Retour 360': 'Kanban - _Terminé - Retour 360', 
      'Data - Prospection': 'Labs - Prospection',
      'Data - Cadrage LLM pour ILB': '_Terminé - Data - ILB - Cadrage LLM pour ILB',
      'Data - POC OCR Annuaires': '_Terminé - Data - ILB - POC OCR Annuaires',
      'Data - BdF - Stabilité financière': '_Terminé - Data - Banque de France - BdF - Stabilité financière - AVENANT 0',
      'Labs - Jour Férié': 'ILB - Jour Férié',
      'Data - Workka': '_Terminé - Data - Workka - Investment strategies backtest - AVENANT 0',
      'Tâche interne récurrente - Documentations Labs': 'Labs - Documentation Labs',
      'Tâche interne récurrente - IT': 'ILB - IT',
      'Data - Plan de développement des Labs': 'Labs - Plan de développement des Labs',
      'Tâche interne récurrente - Outils projets (fiches, template, suivi 360…)': 'Labs - Tâches interne (autres)',
      'Data - Data Viz': 'Data - ILB - Data Viz Bounie',
      'Data - Congés': 'ILB - Congés & Arrêts (hors jours fériés)',
      'Data - Challenge Data': 'Data - Labs - Challenge Data - Beta Testing',
      'tâche interne - Jour férié': 'ILB - Jour Férié',
      'tâche interne - Jour non travaillé': 'ILB - Jour Férié',
      'Data - CDC': 'Data - ILB - CDC',
      'tâche interne - Slides marketing': 'Labs - Documentation Labs',
      'tâche interne - Outil Powerpoint': 'Labs - Tâches interne (autres)',
      'Data - Patrimoine': 'Data - ILB - Patrimoine',
      'tâche interne - Risk Forum': 'Labs - Préparation événement',
      'tâche interne - Offre chercheurs': 'Labs - Tâches interne (autres)',
      'Data - OFEX': 'Data - ILB - OFEX',
      'tâche interne - Onboarding': 'Labs - Tâches interne (autres)',
      'toy project - revue de littérature': 'Data - Labs - Toy project',
      'revue de littérature - frameworks': 'ERREUR',
      'replication modele Merton - analyse white paper chercheur UK': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'replication modele Merton, simulation Monte Carlo, prise en main Catherina': 'Data - Pladifes - Stage Physical Risk',
      'revue littérature, implémenation et modélisation Merton, exploration réplication Bartram': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'exploration et début de réplication Bartram': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'réplication Bartram': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'replication ': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'replication': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'replication, risque physique ': 'Data - Pladifes - Stage Physical Risk',
      'WBS replication, risque physique': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'risque physique': 'Data - Pladifes - Stage Physical Risk',
      'risque physique, WBS': "_Terminé - Data - WBS - Réplication d'un papier - AVENANT 0",
      'tâche interne - Newsletter Datalab': 'Labs - Newsletter Data',
      'Data - Scrapping AAP': 'Data - ILB - Scrapping AAP',
      'tâche interne - OCR BNP PF': '_Terminé - Data - ILB - POC OCR Annuaires',
      'tâche interne - OCR RIVA': '_Terminé - Data - ILB - POC OCR Annuaires',
      'tâche interne - Outil FAQ': 'Labs - Tâches interne (autres)',
      'tâche interne - Handbook': 'Data - Labs - Handbook / Pylb / NL',
      'tâche interne - jours fériés': 'ILB - Jour Férié',
      'tâche interne - Retour clients': 'Labs - Tâches interne (autres)',
      'tâche interne - Pylb': 'Data - Labs - Handbook / Pylb / NL',
      'tâche interne - Git': 'Data - Labs - Handbook / Pylb / NL',
      'Labs - Newsletter Data Lab': 'Labs - Newsletter Data',
      'Data - Handbook / Pylb / NL': 'Data - Labs - Handbook / Pylb / NL',
      "Labs - Préparation présentation d'équipe": "Labs - Préparation présentation d'équipe",
      'ESG - CAPA': 'ESG - CAPA - Tâches Labs/PARC',
      'Labs - Réu CDI': 'Labs - Réunions internes',
      'Labs - Point (EAE, autres)': 'Labs - Réunions internes',
      'tâche interne - Suivi 360': 'Kanban - _Terminé - Retour 360',
      "Labs - Présentation d'équipe": "Labs - Préparation présentation d'équipe",
      'Labs - Réu ESG Lab': 'Labs - Réunions internes',
      'tâche interne - Viz recyclage': 'Labs - Tâches interne (autres)',
      'ESG - CAA Sinistres Immo': 'ESG - CAA Empreinte Immo', 
      'tâche interne - Outil staffing': 'Kanban - _Terminé - Suivi budgétaire projets',
      'ESG - PF Inclusion Financière': '_Terminé - ESG - BNPP PF - PF Inclusion Financière - AVENANT 0',
      'Labs - Réunions RH': 'Labs - RH & suivi collaborateur',
      'Labs - Evénement - orga': 'Labs - Préparation événement',
      'Labs - Réunions génériques': 'Labs - Réunions internes',
      'Labs - Evénement - participation': 'Labs - Participation événement',
      'Labs - PF - Accompagnement stratégique': 'ESG - Accompagnement Stratégique BNPP PF',
      'Labs - Jour férié': 'ILB - Jour Férié',
      'tâche interne - Réunion CDI / Presentations internes': 'Labs - Réunions internes',
      'tâche interne - Réunion suivi collaborateurs (EAE, mi-stages etc.)': 'Labs - RH & suivi collaborateur',
      'tâche interne - Réunion suivi collaborateurs ': 'Labs - RH & suivi collaborateur',
      'tâche interne - Orga weekend séminaire': 'Labs - Préparation événement',
      'Data - BNPP PF Habitat': '_Terminé - ESG - BNPP PF - Habitat - AVENANT 0',
      'tâche interne - Conférences ': 'Labs - Participation événement',
      'tâche interne - Réunion inter-collaborateurs (EAE, mi-stages, consultations etc.)': 'Labs - RH & suivi collaborateur',
      'ESG - PNUD': 'ESG - PNUD - Taxonomie et décarbonation en Tunisie - AVENANT 0',
      'tâche interne - Power BI': 'Labs - PowerBI',
      'tâche interne - Réunion ESG lab ': 'Labs - Réunions internes',
      'ESG - Accompagnement Stratégique BNPP PF': "ESG - Accompagnement Stratégique BNPP PF", 
      'ESG - BNPP PF – Sustainability Market Watch': 'ESG - BNPP PF - Sustainability Market Watch', ##?
      'ESG - BNPP PF - Auto & Travaux B2C': 'ESG - BNPP PF - Auto & Travaux B2C - AVENANT 0',
      'Kanban - Tarification': 'Kanban - _Terminé - Tarification',
      'Data - Kearney scrapping reviews': '_Terminé - Data - Kearney - Scrapping reviews - AVENANT 0',
      'Data - Kearney': '_Terminé - Data - Kearney - Conseil - AVENANT 0',
      'tâche interne - Encadrement stagiaire': 'Labs - RH & suivi collaborateur',
      'tâche interne - Formation': 'Labs - Formation',
      'tâche interne - PyLB': 'Data - Labs - Handbook / Pylb / NL',
      'tâche interne - Conférence': 'Labs - Participation événement',
      'Data - LLM pour ILB': 'Data - Labs - LLM pour ILB',
      'Data - Communication Int/Ext': 'Labs - Communication Int/Ext',
      'Data - FaIR DataViz': 'Data - FAIR - DataViz - AVENANT 0',
      'Data - Dev Pladifes': 'Data - Pladifes - Dev Pladifes',
      'Data - Extractions Refinitiv': 'Labs - Extractions Refinitiv',
      'tâche interne - IT': 'ILB - IT',
      'Data - Alignment cartography': 'Data - PARC - Alignment cartography',
      'Data - Base actifs bottom up': 'Data - Pladifes - Bottom-up',
      'Data - Métaux critiques': 'Data - Pladifes - Métaux critiques',
      'Data - Cyclone': 'Data - Pladifes - Physical Risk - Cyclones',
      'Data - CDP': '_Terminé - Data - Pladifes - CDP',
      'Tâches internes': 'Labs - Tâches interne (autres)',
      'Data - BNPP PF Green': '_Terminé - Data - BNPP PF - Green (ancien)', 
      'Data - CAA Green': '_Terminé - Data - BNPP PF - Green (ancien)', 
      'tâche interne - Conférence / atelier': 'Labs - Participation événement',
      'tâche interne - Point de suivi trimestriel': 'Labs - RH & suivi collaborateur',
      'Férié': 'ILB - Jour Férié',
      'tâche interne - Workka': '_Terminé - Data - Workka - Investment strategies backtest - AVENANT 0',
      'Data - CAA recolte': 'ESG - CAA - Alignement & Empreinte carbone - AVENANT 3',
      'Data - CAA Habitat': 'ESG - CAA - Alignement & Empreinte carbone - AVENANT 4',
      'Data - CAA Automoteur': 'ESG - CAA - Alignement & Empreinte carbone - AVENANT 3',
      'Labs - Evenement ILB': 'Labs - Participation événement',
      'Labs - Réunion esg': 'Labs - Réunions internes',
      'ESG - PARC': 'ESG - PARC - Aides diverses',
      'ESG - CAA Alignement Automobile': '_Terminé - ESG - CAA - Alignement Automobile - AVENANT 0',
      'ESG - FIT': 'ESG - FIT - Forum for Insurance Transition',
      'tâche interne - Reunion CDI': 'Labs - Réunions internes',
      'tâche interne - Atelier - Tests Statistiques ': "Labs - Préparation présentation d'équipe",
      'tâche interne - Outil suivi de projet': 'Kanban - _Terminé - Suivi budgétaire projets',
      'tâche interne - Divers': 'Labs - Tâches interne (autres)',
      'tâche interne - Suivi projet 360': 'Kanban - _Terminé - Retour 360',
      'Kanban - Suivi budgétaire projets': 'Kanban - _Terminé - Suivi budgétaire projets',
      'tâche interne - Autres': 'Labs - Tâches interne (autres)',
      'Data - Physical Risk': 'Data - Pladifes - Physical Risk - Overview',
      'Data - RSE': 'ILB - RSE',
      'Data - Le Mans': '_Terminé - Data - Le Mans Université (chaire ILB) - Projet sécheresse - AVENANT 0',
      'tâche interne - Réunion seniors': 'Labs - Réunions internes',
      'tâche interne - Réunion CDI': 'Labs - Réunions internes',
      'Data - IT': 'ILB - IT',
      'tâche interne - Staffing': 'Labs - Tâches interne (autres)',
      'tâche interne - Suivi 360 projet': 'Kanban - _Terminé - Retour 360',
      'tâche interne - EAE': 'Labs - RH & suivi collaborateur',
      'tâche interne - Challenge data': 'Data - Labs - Challenge Data - Beta Testing',
      'Data - Seyver': 'Data - Seyver - Seyver - AVENANT 0',
      'Jour férié': 'ILB - Jour Férié',
      'Labs - Formations / Conférences': 'Labs - Participation événement',
      'tâche interne - Newsletter': 'Labs - Newsletter ESG', 
      'tâche interne - Procédure arrivée stagiaire': 'Labs - RH & suivi collaborateur',
      'tâche interne - Point de stage': 'Labs - RH & suivi collaborateur',
      "tâche interne - Préparation présentation d'équipe": "Labs - Préparation présentation d'équipe",
      "Champ libre - CAA - Pro": '_Terminé - ESG - CAA - Alignement Pro - AVENANT 0',
      "Champ libre - ESG - Appel d'offre": 'Labs - Prospection', 
      "Champ libre - Arval - Biocarburants": 'ESG - Arval - Biocarburants Brésil - AVENANT 0', 
      "Champ libre - Projet BDD Admin": 'ILB - Projet BDD Admin', 
      "Champ libre - Demo Viz map": "Data - ILB - Data Viz Bounie",
      "Champ libre - Syever": 'Data - Seyver - Seyver - AVENANT 0',
      "Champ libre - Séminaire": 'Labs - Préparation événement', 
      "Champ libre - Revue d'articles \"medium\" sur les LLM": 'Data - Labs - LLM pour ILB',
      "Champ libre - Supervision présentation d'équipe Ilias": "Labs - Préparation présentation d'équipe",
      "Champ libre - plan développement": 'Labs - Plan de développement des Labs',
      "Champ libre - Résoudre les problèmes techniques du PC": 'ILB - IT', 
      "Champ libre - Labs - Séminaire": 'Labs - Préparation événement',
      "Champ libre - ESG - PNUD": 'ESG - PNUD - Taxonomie et décarbonation en Tunisie - AVENANT 0',
      "Champ libre - ESG - Emissions facilitées": 'Labs - Prospection',
      "Champ libre - ESG - Accompagnement Article & Presentation d'equipe stagiaires": 'Labs - Préparation présentation d\'équipe',
      "Champ libre - ESG - Encadrement stagiaires": '', # Lina: split 33/33/33 entre RH / ESG - Arval - Biocarburants Brésil - AVENANT 0 / _Terminé - ESG - BNP PF - Habitat - AVENANT 0
      "Champ libre - ESG - ARVAL": 'ESG - Arval - Biocarburants Brésil - AVENANT 0', 
      "Champ libre - CAA - Professionnel / entreprise": '_Terminé - ESG - CAA - Alignement Pro-Entreprise - AVENANT 0', #direct nouveau nom, pas d'ancien
      "Champ libre - Mémoire - Alignement d'un portefeuille Assurance récolte": 'ESG - CAA - Alignement & Empreinte carbone - AVENANT 3',

      "Data - Risques physique": 'Data - Pladifes - Physical Risk - Cyclones', 
      "Data - Seyver - OCR Cartes grises": 'Data - Seyver - Seyver - AVENANT 0',
      "Data -  LLM pour ILB": 'Data - Labs - LLM pour ILB',

      "ESG - CAA Alignement Pro-Entreprise": '_Terminé - ESG - CAA - Alignement Pro-Entreprise - AVENANT 0',
      "ESG - GSF": '_Terminé - ESG - GSF - Aides diverses',
      "ESG - Projet ENPC": 'ESG - ILB - ENPC',
      "ESG - CAA Sinistres Auto": '_Terminé - ESG - CAA - Sinistres Auto - AVENANT 0',
      "ESG - EDF Alignement Climatique": '_Terminé - ESG - EDF - Alignement Climatique - AVENANT 0', 
      "ESG - CAA Emissions Sinistres": '_Terminé - ESG - CAA - Emission Sinistres - AVENANT 0', 
      "ESG - BNPP PF Habitat": '_Terminé - ESG - BNPP PF - Habitat - AVENANT 0',
      "ESG - Jeux Gestion Ptf ESG": 'ESG - ILB - Jeux Gestion Ptf ESG',
      "ESG - Empreinte Carbone ILB": 'ESG - ILB - Empreinte Carbone ILB',
      "ESG - Newsletter": 'Labs - Newsletter ESG',
      "ESG - CAA Alignement Pro": '_Terminé - ESG - CAA - Alignement Pro - AVENANT 0',
      "ESG - Market Watch": 'ESG - BNPP PF - Sustainability Market Watch',
      "ESG - CAA Sinistre International": 'ESG - CAA - Alignement & Empreinte carbone - AVENANT 4',
      "ESG - CAA Alignement Auto": '_Terminé - ESG - CAA - Alignement Automobile - AVENANT 0', 
      "ESG- BNPP PF Habitat": '_Terminé - ESG - BNPP PF - Habitat - AVENANT 0', 
      "ESG - BNPP PF": 'ESG - BNPP PF - ERREUR'
}


def correct_aggregated_old_excels(raw_aggregated_public_archives, translation_dict=translation_dict):
    
    corrected_aggregated_public_archives = raw_aggregated_public_archives.copy()
    
    corrected_projects = corrected_aggregated_public_archives["Projet ?"].fillna("ESG - Arval - Biocarburants Brésil - AVENANT 0")
    corrected_aggregated_public_archives["Projet ?"] = corrected_projects.replace(translation_dict)

    specifics = [
        [
            "ESG - BNPP PF - Sustainability Market Watch", 
            ["_Terminé - ESG - BNPP PF - Sustainability Market Watch - AVENANT 0", "ESG - BNPP PF - Sustainability Market Watch - AVENANT 1"],
            pd.to_datetime("01/08/2024", format="%d/%m/%Y")
        ],[
            "ESG - Accompagnement Stratégique BNPP PF",
            ["ESG - BNPP PF - Accompagnement Stratégique - AVENANT 0", "ESG - BNPP PF - Accompagnement Stratégique - AVENANT 1"],
            pd.to_datetime("01/07/2024", format="%d/%m/%Y")
        ],[
        "ESG - CAA Empreinte Immo",
        ["ESG - CAA - Alignement & Empreinte carbone de sinistres - AVENANT 3", "ESG - CAA - Alignement & Empreinte carbone de sinistres - AVENANT 4"],
            pd.to_datetime("28/06/2024", format="%d/%m/%Y") 
        ],[
        "ESG - PF Alignement Auto",
        ["_Terminé - ESG - BNPP PF - Alignement Auto - AVENANT 2", "_Terminé - ESG - BNPP PF - Alignement Auto - AVENANT 3"],
            pd.to_datetime("15/03/2024", format="%d/%m/%Y") 
        ],[
        "Data - BNPP PF Data RCS",
        ["_Terminé - Data - BNPP PF - Data RCS - AVENANT 5", "_Terminé - Data - BNPP PF - Data RCS - AVENANT 6"],
            pd.to_datetime("17/06/2024", format="%d/%m/%Y") 
        ]
    ]

    project_column = corrected_aggregated_public_archives["Projet ?"].values
    for old_name, new_names, shift_date in specifics:
        mask_temp = (corrected_aggregated_public_archives["Projet ?"]==old_name)
        mask_1 = mask_temp & (corrected_aggregated_public_archives["Date"]<=shift_date)
        mask_2 = mask_temp & (corrected_aggregated_public_archives["Date"]>shift_date)
        project_column[mask_1] = new_names[0]
        project_column[mask_2] = new_names[1]
        
    corrected_aggregated_public_archives["Projet ?"] = project_column
    
    return corrected_aggregated_public_archives